# Generated by Django 5.1.1 on 2024-10-11 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contratante', models.CharField(max_length=50)),
                ('objeto', models.TextField(max_length=1200)),
                ('origem', models.CharField(max_length=50)),
                ('processo', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50)),
                ('seguro', models.BooleanField(default=False, verbose_name=' Sim /Não')),
                ('apolice', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Apólice')),
                ('seguradora', models.CharField(blank=True, max_length=100, null=True, verbose_name='Seguradora')),
                ('inicio', models.DateTimeField()),
                ('vigencia', models.CharField(max_length=50)),
                ('fim_contrato', models.DateTimeField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor Total')),
                ('observacoes', models.TextField(max_length=1800)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_entrega', models.DateField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='contracts.contratos')),
            ],
        ),
    ]
