# Generated by Django 5.1.1 on 2024-10-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='seguro',
            field=models.BooleanField(default=False, verbose_name=' Seguro'),
        ),
    ]
