# Generated by Django 5.1.1 on 2024-10-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=15)),
                ('data', models.DateTimeField()),
                ('modalidade', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('objeto', models.TextField(max_length=1800)),
                ('descrição', models.TextField(max_length=1800)),
            ],
        ),
    ]
