# Generated by Django 5.1.1 on 2024-10-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='modalidade',
            field=models.CharField(max_length=100),
        ),
    ]
